<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate( 'central.site.list.title', 'central' ) );
$view       = $this;
$rowSet     = $this->rowSet();
$domainLink = function ( $domain ) use ( $view ) {
    return '<a target="_blank" href="http://'
         . $view->escapeHtmlAttr( $domain ) . '">'
         . $view->escapeHtml( $domain ) . '</a>';
};

if ( ! $this->format ): ?>
<h1><?= $title ?></h1>
<?php endif ?>
<?= $this->rowSet( $this->paginator, $rowSet::FLAG_LAYOUT_ALL )
         ->setColumnTranslatePrefix( 'central.site.list.column' )
         ->setColumnTranslatePostfix( 'title' )
         ->setColumnTranslateTextDomain( 'central' )
         ->setPage( $this->page )
         ->setColumns( array(
              'id'              => $rowSet::INT,
              'schema'          => $rowSet::STRING,
              'domains'         => function ( $row ) use ( $domainLink ) {
                  return implode(
                      '<br />' . PHP_EOL,
                      array_map( $domainLink, $row->domains )
                  );
              },
              'ownerEmail'      => $rowSet::STRING,
              'created'         => $rowSet::DATETIME,
          ) )
         ->render( $this->format );
