<?php

$this->headLink()
     ->appendStylesheet( '/styles/central.css', 'all' );

$paginationControl = $this->paginationControl(
    $this->paginator
         ->setCurrentPageNumber( $this->page ),
    'Sliding',
    'paginator/default'
);

?>
<div class="paragraph-like MultisiteCentral siteList">
    <h3><?= $this->translate( 'central.site.list.title', 'central' ) ?></h3>
    <form action="?" method="post">
        <?= $paginationControl ?>

        <table class="list max-width no-border">
<?php if ( ! $this->paginator->getTotalItemCount() ): ?>

            <tfoot>
                <tr class="empty">
                    <td class="info">
                        <i><?= $this->translate( 'central.site.noData', 'central' ) ?></i>
                    </td>
                </tr>
            </tfoot>
<?php else: ?>
            <tbody>
<?php foreach ( $this->paginator as $row ): ?>

                <tr class="row">
                    <td class="field field-domain">
<?php foreach ( $row->domains as $domain ): ?>

                        <a href="<?= $this->url(
                                'Grid\MultisitePlatform\AutoLogin\ByDomain',
                                array(
                                    'locale'    => (string) $this->locale(),
                                    'domain'    => $domain,
                                )
                            ) ?>"><?= $domain ?></a><br />
<?php endforeach ?>

                    </td>
                    <td class="field field-created">
                        <?= $this->dateFormat(
                                new \DateTime( $row->created ),
                                \IntlDateFormatter::LONG,
                                \IntlDateFormatter::LONG
                        ) ?>
                    </td>
                    <td class="field field-actions">
                        <a class="action-button delete"
                           title="<?= $this->translate( 'default.delete' ) ?>"
                           onclick="return js.require('js.ui.dialog').confirm(this);"
                           href="/app/<?= $this->locale() ?>/central/delete-site/<?= $row->id ?>">&nbsp;</a>
                    </td>
                </tr>
<?php endforeach ?>

            </tbody>
<?php endif ?>

        </table>
        <?= $paginationControl ?>

    </form>
    <?= $this->viewWidget( 'Grid\MultisiteCentral\Welcome\SiteList', '', array(
        'user' => $this->user,
    ) ) ?>

</div>
