<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate( 'domain.list.title', 'domain' ) );
$view       = $this;
$rowSet     = $this->rowSet();
$actualId   = $this->appService( 'Zork\Db\SiteInfo' )
                   ->getDomainId();

if ( ! $this->format ): ?>
<h1><?= $title ?></h1>
<?php endif ?>
<?= $this->rowSet( $this->paginator, $rowSet::FLAG_LAYOUT_ALL )
         ->setColumnTranslatePrefix( 'domain.list.column' )
         ->setColumnTranslatePostfix( 'title' )
         ->setColumnTranslateTextDomain( 'domain' )
         ->setPage( $this->page )
         ->setColumns( array(
              'domain'  => $rowSet::STRING,
              'idn'     => function ( $row ) {
                return @ idn_to_utf8( $row->domain );
              },
              'actions' => function ( $row ) use ( $view, $actualId ) {
                $view->placeholder( 'listActions' )->set( '' );
                $view->placeholder( 'listActions' )->captureStart();
?>
    <a class="action-button view" target="_blank"
       title="<?= $view->translate( 'default.view' ) ?>"
       href="http://<?= $row->domain ?>">
    </a>
<?php if ( $row->id != $actualId ): ?>
<?php if ( $this->isAllowed( 'domain', 'edit' ) ): ?>
    <a class="action-button edit"
       title="<?= $view->translate( 'default.edit' ); ?>"
       href="/app/<?= $view->locale() ?>/admin/domain/edit/<?= $row->id ?>">
    </a>
<?php endif ?>
<?php if ( $this->isAllowed( 'domain', 'delete' ) ): ?>
    <a class="action-button delete"
       title="<?= $view->translate( 'default.delete' ); ?>"
       href="/app/<?= $view->locale() ?>/admin/domain/delete/<?= $row->id ?>"
       onclick="return js.require('js.ui.dialog').confirm(this);">
    </a>
<?php endif ?>
<?php endif ?>
<?php
                $view->placeholder( 'listActions' )->captureEnd();
                return (string) $view->placeholder( 'listActions' );
              },
          ) )
         ->render( $this->format );

if ( ! $this->format && $this->isAllowed( 'domain', 'create' ) ): ?>
<div class="more-links">
    <a class="button-appearance"
       href="/app/<?= $view->locale() ?>/admin/domain/create">
        <?= $view->translate( 'default.createNew' ); ?>
    </a>
</div>
<?php endif ?>
