<div class="paragraph-like MultisiteCentral confirm">
    <h3><?= $this->translate( 'central.site.create.confirm.title', 'central' ) ?></h3>
<?php if ( $this->success ): ?>

    <p class="info">
        <?= $this->translate( 'central.site.create.confirm.successful', 'central' ) ?>
        <br />
        <a href="/app/<?= $this->locale() ?>/central/site-wizard/check?hash=<?= $this->escapeHtmlAttr( $this->hash ) ?>"
           target="_blank" data-js-type="js.central.site.confirmed">
            <?= $this->translate( 'central.site.create.confirm.createSite', 'central' ) ?>
        </a>
    </p>
<?php else: ?>

    <p class="warn">
        <?= $this->translate( 'central.site.create.confirm.failed', 'central' ) ?>

    </p>
<?php endif ?>

</div>
