<?php $this->headLink()
           ->appendStylesheet( '/styles/wizard.css', 'all' );

?><div class="wizard">
    <div class="wizard-step">
        <ul class="step-stack ui-helper-clearfix">
            <li><a href="#"><?= $this->translate( 'default.finish' ) ?></a></li>
        </ul>
        <div class="step-action step-action-finish">
        <?php if ( ! empty( $this->error ) ): ?>
            <div data-js-type="zork.wizard.cancel">
                <?= $this->translate( 'central.site.create.error', 'central' ) ?>
                <?php if ( ! empty( $this->message ) ): ?>
                    <?= $this->translate( $this->message, 'central' ) ?>
                <?php endif ?>

            </div>
        <?php else: ?>

            <div data-js-type="zork.wizard.finish">
                <?= sprintf( $this->translate( 'central.site.create.finish', 'central' ),
                             $this->url, $this->domain ) ?>
            </div>
        <?php endif ?>

        </div>
    </div>
</div>
