<?php if ( ! empty( $this->error ) ): ?>
<div class="wizard" data-js-type="zork.wizard.cancel">
    <?= $this->translate( 'central.site.create.error', 'central' ) ?>
    <?php if ( ! empty( $this->message ) ): ?>
        <?= $this->translate( $this->message, 'central' ) ?>
    <?php endif ?>
</div>
<?php else: ?>
<div class="wizard" data-js-type="zork.wizard.finish">
    <?= sprintf( $this->translate( 'central.site.create.finish', 'central' ),
                 $this->url, $this->domain ) ?>
</div>
<?php endif ?>
