<?php

/**
 * @var Zend\View\Renderer\PhpRenderer $this
 */

$links = $this->headLink()
              ->getContainer()
              ->getArrayCopy();

foreach ( $links as $index => $item )
{
    if ( ! empty( $item->id ) &&
           'customizeStyleSheet' === $item->id )
    {
        $this->headLink()
             ->getContainer()
             ->offsetUnset( $index );
    }
}

$this->headLink()
     ->appendStylesheet( '/styles/admin.css', 'all' );

$menu = $this->navigation( $this->navigationPages )
             ->setAcl( $this->acl )
             ->menu()
             ->setTranslatorEnabled( false );

$this->headTitle()
     ->prepend( $title = $this->translate(
            'admin.notAllowed.title',
            'admin'
        ) );

if ( $this->hasIdentity ): ?>

    <header>
        <nav class="menu"
             data-js-type="zork.ui.menu"
             data-js-menu-corners="bottom"
             data-js-menu-orientation="horizontal">
            <?= $menu->render() ?>
        </nav>
    </header>

    <div class="adminContentContainer"><?php
        $ns = array_map( 'lcfirst', explode( '\\' , $this->controller ) );
        $controller = array_pop( $ns );
    ?>

        <section class="multisite admin <?=
                 implode( '-', $ns ) . '-ns' ?> <?=
                 $controller . '-controller' ?> <?=
                 $this->action . '-action'; ?>">
<?php endif ?>

            <h1 class="prefix"><?= $this->escapeHtml( $title ) ?></h1>
<?= $this->content ?>

<?php if ( $this->hasIdentity ): ?>
            <br class="clear" />
        </section>
    </div>
<?php endif ?>
